### ISSUE TITLE
'utf-8' codec can't decode byte 0xc7 in position 3679: invalid continuation byte

### ISSUE THREAD

**Issue by RuizSerra** [giovannicoppola/zothero#10]
ZotHero crashes with `'utf-8' codec can't decode byte 0xc7 in position 3679: invalid continuation byte`.

<img width="764" alt="image" src="https://user-images.githubusercontent.com/71858495/193696798-38e11525-d8ec-47a3-b3ef-9e51a2cb64d2.png">

Debugging output:
```
[09:51:45.992] Logging Started...
[09:51:48.467] ZotHero[Script Filter] Queuing argument 'f'
[09:51:48.591] ZotHero[Script Filter] Script with argv 'f' finished
[09:51:48.593] STDERR: ZotHero[Script Filter] .
09:51:48 workflow.py:2093 DEBUG    ---------- ZotHero (1.99.7) ----------
09:51:48 zh.py:705 DEBUG    args={'--bibliography': False,
 '--help': False,
 '--paste': False,
 '--style': None,
 '--text': None,
 '--title': None,
 '<citekey>': None,
 '<id>': None,
 '<key>': None,
 '<query>': 'f',
 '<style>': None,
 '<value>': None,
 'attachments': False,
 'citations': False,
 'clear': False,
 'config': False,
 'copy': False,
 'fields': False,
 'locale': False,
 'notify': False,
 'reindex': False,
 'search': True,
 'setvar': False,
 'style': False}
09:51:48 config.py:89 DEBUG    [config] attachdir='/Users/jaime/Library/CloudStorage/GoogleDrive-jaimeruizno@gmail.com/My Drive/Zotero'
09:51:48 config.py:86 DEBUG    [config] datadir='/Users/jaime/Zotero'
09:51:48 workflow.py:2114 ERROR    'utf-8' codec can't decode byte 0xc7 in position 3679: invalid continuation byte
Traceback (most recent call last):
  File "/Users/jaime/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.685652EF-1B61-4C2A-BCC0-7F8255FF6CF6/lib/workflow/workflow.py", line 2107, in run
    func(self)
  File "/Users/jaime/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.685652EF-1B61-4C2A-BCC0-7F8255FF6CF6/zh.py", line 719, in main
    app = zothero.ZotHero(wf.cachedir, datadir, attachdir)
  File "/Users/jaime/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.685652EF-1B61-4C2A-BCC0-7F8255FF6CF6/lib/zothero/core.py", line 62, in __init__
    datadir, attachdir = read_config()
  File "/Users/jaime/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.685652EF-1B61-4C2A-BCC0-7F8255FF6CF6/lib/zothero/config.py", line 35, in read
    return parse_prefs(p)
  File "/Users/jaime/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.685652EF-1B61-4C2A-BCC0-7F8255FF6CF6/lib/zothero/config.py", line 73, in parse_prefs
    for line in fp:
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc7 in position 3679: invalid continuation byte
09:51:48 workflow.py:2116 INFO     for assistance, see: https://github.com/giovannicoppola/zothero/issues
09:51:48 workflow.py:2136 DEBUG    ---------- finished in 0.017s ----------
[09:51:48.596] ZotHero[Script Filter] {
  "items": [
    {
      "title": "Error in workflow 'ZotHero'",
      "subtitle": "'utf-8' codec can't decode byte 0xc7 in position 3679: invalid continuation byte",
      "valid": false,
      "icon": {
        "path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
      }
    }
  ]
}
```

**Comment by giovannicoppola** [comment]
could you try the most recent version?

**Comment by jaekyeom** [comment]
Afaik, this could happen due to the way Zutilo saves (user-defined) shortcuts in `prefs.js`.
