### ISSUE TITLE
'utf-8' codec can't decode byte 0xae in position 2540: invalid continuation byte

### ISSUE THREAD

**Issue by cdoppler** [giovannicoppola/zothero#16]
ZotHero v.1.99.7 + Alfred 4.8 [1312] crashes: `'utf-8' codec can't decode byte 0xae in position 2540: invalid continuation byte`

 <img width="579" alt="Bildschirm­foto 2022-12-27 um 20 17 14" src="https://user-images.githubusercontent.com/65411163/209712681-a3e21164-19a2-499a-ae1c-9d54eb25c96f.png">

Debugging output:
[20:15:52.685] Logging Started...
[20:15:56.792] ZotHero[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.F091CFD6-0B52-47CE-8878-7AE06D9BD839%3E674740C4-BFDA-44C8-A478-586EF06217BF)] Queuing argument ''
[20:15:56.917] ZotHero[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.F091CFD6-0B52-47CE-8878-7AE06D9BD839%3E674740C4-BFDA-44C8-A478-586EF06217BF)] Script with argv '' finished
[20:15:56.919] STDERR: ZotHero[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.F091CFD6-0B52-47CE-8878-7AE06D9BD839%3E674740C4-BFDA-44C8-A478-586EF06217BF)] .
20:15:56 workflow.py:2093 DEBUG    ---------- ZotHero (1.99.7) ----------
20:15:56 zh.py:705 DEBUG    args={'--bibliography': False,
 '--help': False,
 '--paste': False,
 '--style': None,
 '--text': None,
 '--title': None,
 '<citekey>': None,
 '<id>': None,
 '<key>': None,
 '<query>': '',
 '<style>': None,
 '<value>': None,
 'attachments': False,
 'citations': False,
 'clear': False,
 'config': True,
 'copy': False,
 'fields': False,
 'locale': False,
 'notify': False,
 'reindex': False,
 'search': False,
 'setvar': False,
 'style': False}
20:15:56 config.py:89 DEBUG    [config] attachdir='/Users/cdoppler/OneDrive/Zotero'
20:15:56 config.py:86 DEBUG    [config] datadir='/Users/cdoppler/Zotero'
20:15:56 workflow.py:2114 ERROR    'utf-8' codec can't decode byte 0xae in position 2540: invalid start byte
Traceback (most recent call last):
  File "/Users/cdoppler/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.F091CFD6-0B52-47CE-8878-7AE06D9BD839/lib/workflow/workflow.py", line 2107, in run
    func(self)
  File "/Users/cdoppler/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.F091CFD6-0B52-47CE-8878-7AE06D9BD839/zh.py", line 719, in main
    app = zothero.ZotHero(wf.cachedir, datadir, attachdir)
  File "/Users/cdoppler/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.F091CFD6-0B52-47CE-8878-7AE06D9BD839/lib/zothero/core.py", line 62, in __init__
    datadir, attachdir = read_config()
  File "/Users/cdoppler/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.F091CFD6-0B52-47CE-8878-7AE06D9BD839/lib/zothero/config.py", line 35, in read
    return parse_prefs(p)
  File "/Users/cdoppler/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.F091CFD6-0B52-47CE-8878-7AE06D9BD839/lib/zothero/config.py", line 73, in parse_prefs
    for line in fp:
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xae in position 2540: invalid start byte
20:15:56 workflow.py:2116 INFO     for assistance, see: https://github.com/giovannicoppola/zothero/issues
20:15:56 workflow.py:2136 DEBUG    ---------- finished in 0.034s ----------
[20:15:56.921] ZotHero[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.F091CFD6-0B52-47CE-8878-7AE06D9BD839%3E674740C4-BFDA-44C8-A478-586EF06217BF)] {
  "items": [
    {
      "title": "Error in workflow 'ZotHero'",
      "subtitle": "'utf-8' codec can't decode byte 0xae in position 2540: invalid start byte",
      "valid": false,
      "icon": {
        "path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
      }
    }
  ]
}
[20:17:09.275] ZotHero[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.F091CFD6-0B52-47CE-8878-7AE06D9BD839%3E674740C4-BFDA-44C8-A478-586EF06217BF)] Queuing argument ''
[20:17:09.466] ZotHero[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.F091CFD6-0B52-47CE-8878-7AE06D9BD839%3E674740C4-BFDA-44C8-A478-586EF06217BF)] Script with argv '' finished
[20:17:09.473] STDERR: ZotHero[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.F091CFD6-0B52-47CE-8878-7AE06D9BD839%3E674740C4-BFDA-44C8-A478-586EF06217BF)] .
20:17:09 workflow.py:2093 DEBUG    ---------- ZotHero (1.99.7) ----------
20:17:09 zh.py:705 DEBUG    args={'--bibliography': False,
 '--help': False,
 '--paste': False,
 '--style': None,
 '--text': None,
 '--title': None,
 '<citekey>': None,
 '<id>': None,
 '<key>': None,
 '<query>': '',
 '<style>': None,
 '<value>': None,
 'attachments': False,
 'citations': False,
 'clear': False,
 'config': True,
 'copy': False,
 'fields': False,
 'locale': False,
 'notify': False,
 'reindex': False,
 'search': False,
 'setvar': False,
 'style': False}
20:17:09 config.py:89 DEBUG    [config] attachdir='/Users/cdoppler/OneDrive/Zotero'
20:17:09 config.py:86 DEBUG    [config] datadir='/Users/cdoppler/Zotero'
20:17:09 workflow.py:2114 ERROR    'utf-8' codec can't decode byte 0xae in position 2540: invalid start byte
Traceback (most recent call last):
  File "/Users/cdoppler/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.F091CFD6-0B52-47CE-8878-7AE06D9BD839/lib/workflow/workflow.py", line 2107, in run
    func(self)
  File "/Users/cdoppler/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.F091CFD6-0B52-47CE-8878-7AE06D9BD839/zh.py", line 719, in main
    app = zothero.ZotHero(wf.cachedir, datadir, attachdir)
  File "/Users/cdoppler/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.F091CFD6-0B52-47CE-8878-7AE06D9BD839/lib/zothero/core.py", line 62, in __init__
    datadir, attachdir = read_config()
  File "/Users/cdoppler/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.F091CFD6-0B52-47CE-8878-7AE06D9BD839/lib/zothero/config.py", line 35, in read
    return parse_prefs(p)
  File "/Users/cdoppler/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.F091CFD6-0B52-47CE-8878-7AE06D9BD839/lib/zothero/config.py", line 73, in parse_prefs
    for line in fp:
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xae in position 2540: invalid start byte
20:17:09 workflow.py:2116 INFO     for assistance, see: https://github.com/giovannicoppola/zothero/issues
20:17:09 workflow.py:2136 DEBUG    ---------- finished in 0.033s ----------
[20:17:09.476] ZotHero[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.F091CFD6-0B52-47CE-8878-7AE06D9BD839%3E674740C4-BFDA-44C8-A478-586EF06217BF)] {
  "items": [
    {
      "title": "Error in workflow 'ZotHero'",
      "subtitle": "'utf-8' codec can't decode byte 0xae in position 2540: invalid start byte",
      "valid": false,
      "icon": {
        "path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
      }
    }
  ]
}

**Comment by giovannicoppola** [comment]
@cdoppler sorry I missed this. were you able to get it to work?

**Comment by cdoppler** [comment]
Never mind. Actually I didn’t get it to work but I switched to Raycast anyway. 😉
