### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by Faris-2023** [giovannicoppola/zothero#21]
Hi,

First of all, thank you so much for your great workflow.
Since I have a new Mac (with Ventura) I installed ZotHero but it doesn't work anymore. this is the debugger report:

[14:36:18.252] ZotHero[Script Filter] Queuing argument 'p'
[14:36:18.363] ZotHero[Script Filter] Script with argv 'p' finished
[14:36:18.369] STDERR: ZotHero[Script Filter] .
14:36:18 workflow.py:2093 DEBUG    ---------- ZotHero (2.1.0) ----------
14:36:18 zh.py:684 DEBUG    args={'--bibliography': False,
 '--help': False,
 '--paste': False,
 '--style': None,
 '--text': None,
 '--title': None,
 '<citekey>': None,
 '<id>': None,
 '<key>': None,
 '<query>': 'p',
 '<style>': None,
 '<value>': None,
 'attachments': False,
 'citations': False,
 'clear': False,
 'config': False,
 'copy': False,
 'fields': False,
 'locale': False,
 'notify': False,
 'reindex': False,
 'search': True,
 'setvar': False,
 'style': False}
14:36:18 config.py:86 DEBUG    [config] datadir='/Users/farisal-mawwashi/Zotero'
14:36:18 core.py:73 DEBUG    [core] cachedir='~/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/giovanni-zothero'
14:36:18 core.py:74 DEBUG    [core] zotero_dir='~/Zotero'
14:36:18 core.py:75 DEBUG    [core] attachments_dir=None
14:36:18 core.py:137 DEBUG    [core] storage='~/Zotero/storage'
14:36:18 core.py:138 DEBUG    [core] styles='~/Zotero/styles'
14:36:18 cache.py:311 DEBUG    [cache] opening store 'styles'...
14:36:18 cache.py:311 DEBUG    [cache] opening store 'modtimes'...
14:36:18 zh.py:117 DEBUG    Citation style: Chicago Manual of Style 17th edition (author-date)
14:36:18 zotero.py:225 DEBUG    [zotero] database last modified 8.1 mins ago
14:36:18 index.py:202 DEBUG    [index] last updated 6.8 mins ago
14:36:18 index.py:153 DEBUG    [index] opened '~/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/giovanni-zothero/search.sqlite'
14:36:18 index.py:301 DEBUG    [index] updating '~/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/giovanni-zothero/search.sqlite' ...
14:36:18 zotero.py:199 DEBUG    [zotero] opened database '~/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/giovanni-zothero/zotero.sqlite'
14:36:18 zotero.py:320 DEBUG    [zotero] + "Facing Poetry: Alexander Gottlieb Baumgarten's Theory of Literature"
14:36:18 util.py:151 DEBUG    [util] copying '~/Zotero/better-bibtex.sqlite' to '~/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/giovanni-zothero/better-bibtex.sqlite' ...
14:36:18 workflow.py:2114 ERROR    [Errno 2] No such file or directory: '/Users/farisal-mawwashi/Zotero/better-bibtex.sqlite'
Traceback (most recent call last):
  File "/Users/farisal-mawwashi/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.E5ECFFE7-697F-4C98-91B0-47D2F8146ED3/lib/workflow/workflow.py", line 2107, in run
    func(self)
  File "/Users/farisal-mawwashi/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.E5ECFFE7-697F-4C98-91B0-47D2F8146ED3/zh.py", line 734, in main
    return do_search(query)
           ^^^^^^^^^^^^^^^^
  File "/Users/farisal-mawwashi/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.E5ECFFE7-697F-4C98-91B0-47D2F8146ED3/zh.py", line 130, in do_search
    if app.stale and not running:
       ^^^^^^^^^
  File "/Users/farisal-mawwashi/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.E5ECFFE7-697F-4C98-91B0-47D2F8146ED3/lib/zothero/core.py", line 166, in stale
    if self.index.empty:
       ^^^^^^^^^^
  File "/Users/farisal-mawwashi/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.E5ECFFE7-697F-4C98-91B0-47D2F8146ED3/lib/zothero/core.py", line 159, in index
    self._index.update(self.zotero)
  File "/Users/farisal-mawwashi/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.E5ECFFE7-697F-4C98-91B0-47D2F8146ED3/lib/zothero/index.py", line 277, in update
    if not self._update(zot, force):
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/farisal-mawwashi/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.E5ECFFE7-697F-4C98-91B0-47D2F8146ED3/lib/zothero/index.py", line 325, in _update
    for e in it:
  File "/Users/farisal-mawwashi/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.E5ECFFE7-697F-4C98-91B0-47D2F8146ED3/lib/zothero/zotero.py", line 292, in all_entries
    yield self._load_entry(row)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/farisal-mawwashi/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.E5ECFFE7-697F-4C98-91B0-47D2F8146ED3/lib/zothero/zotero.py", line 344, in _load_entry
    e.citekey = self.bbt.citekey('{}_{}'.format(e.library, e.key))
                ^^^^^^^^
  File "/Users/farisal-mawwashi/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.E5ECFFE7-697F-4C98-91B0-47D2F8146ED3/lib/zothero/zotero.py", line 209, in bbt
    self.bibpath_copy = copyifnewer(self.originalBib, self.bibpath)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/farisal-mawwashi/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.E5ECFFE7-697F-4C98-91B0-47D2F8146ED3/lib/zothero/util.py", line 153, in copyifnewer
    copyfile(source, copy)
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/shutil.py", line 256, in copyfile
    with open(src, 'rb') as fsrc:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/farisal-mawwashi/Zotero/better-bibtex.sqlite'
14:36:18 workflow.py:2116 INFO     for assistance, see: https://github.com/giovannicoppola/zothero/issues
14:36:18 workflow.py:2136 DEBUG    ---------- finished in 0.032s ----------
[14:36:18.370] ZotHero[Script Filter] {
  "items": [
    {
      "title": "Error in workflow 'ZotHero'",
      "subtitle": "[Errno 2] No such file or directory: '/Users/farisal-mawwashi/Zotero/better-bibtex.sqlite'",
      "valid": false,
      "icon": {
        "path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
      }
    }
  ]
}
[14:36:18.433] ZotHero[Script Filter] Queuing argument 'po'
[14:36:18.515] ZotHero[Script Filter] Script with argv 'po' finished
[14:36:18.522] STDERR: ZotHero[Script Filter] .
14:36:18 workflow.py:2093 DEBUG    ---------- ZotHero (2.1.0) ----------
14:36:18 zh.py:684 DEBUG    args={'--bibliography': False,
 '--help': False,
 '--paste': False,
 '--style': None,
 '--text': None,
 '--title': None,
 '<citekey>': None,
 '<id>': None,
 '<key>': None,
 '<query>': 'po',
 '<style>': None,
 '<value>': None,
 'attachments': False,
 'citations': False,
 'clear': False,
 'config': False,
 'copy': False,
 'fields': False,
 'locale': False,
 'notify': False,
 'reindex': False,
 'search': True,
 'setvar': False,
 'style': False}
14:36:18 config.py:86 DEBUG    [config] datadir='/Users/farisal-mawwashi/Zotero'
14:36:18 core.py:73 DEBUG    [core] cachedir='~/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/giovanni-zothero'
14:36:18 core.py:74 DEBUG    [core] zotero_dir='~/Zotero'
14:36:18 core.py:75 DEBUG    [core] attachments_dir=None
14:36:18 core.py:137 DEBUG    [core] storage='~/Zotero/storage'
14:36:18 core.py:138 DEBUG    [core] styles='~/Zotero/styles'
14:36:18 cache.py:311 DEBUG    [cache] opening store 'styles'...
14:36:18 cache.py:311 DEBUG    [cache] opening store 'modtimes'...
14:36:18 zh.py:117 DEBUG    Citation style: Chicago Manual of Style 17th edition (author-date)
14:36:18 zotero.py:225 DEBUG    [zotero] database last modified 8.1 mins ago
14:36:18 index.py:202 DEBUG    [index] last updated 6.8 mins ago
14:36:18 index.py:153 DEBUG    [index] opened '~/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/giovanni-zothero/search.sqlite'
14:36:18 index.py:301 DEBUG    [index] updating '~/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/giovanni-zothero/search.sqlite' ...
14:36:18 zotero.py:199 DEBUG    [zotero] opened database '~/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/giovanni-zothero/zotero.sqlite'
14:36:18 zotero.py:320 DEBUG    [zotero] + "Facing Poetry: Alexander Gottlieb Baumgarten's Theory of Literature"
14:36:18 util.py:151 DEBUG    [util] copying '~/Zotero/better-bibtex.sqlite' to '~/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/giovanni-zothero/better-bibtex.sqlite' ...
14:36:18 workflow.py:2114 ERROR    [Errno 2] No such file or directory: '/Users/farisal-mawwashi/Zotero/better-bibtex.sqlite'
Traceback (most recent call last):
  File "/Users/farisal-mawwashi/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.E5ECFFE7-697F-4C98-91B0-47D2F8146ED3/lib/workflow/workflow.py", line 2107, in run
    func(self)
  File "/Users/farisal-mawwashi/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.E5ECFFE7-697F-4C98-91B0-47D2F8146ED3/zh.py", line 734, in main
    return do_search(query)
           ^^^^^^^^^^^^^^^^
  File "/Users/farisal-mawwashi/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.E5ECFFE7-697F-4C98-91B0-47D2F8146ED3/zh.py", line 130, in do_search
    if app.stale and not running:
       ^^^^^^^^^
  File "/Users/farisal-mawwashi/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.E5ECFFE7-697F-4C98-91B0-47D2F8146ED3/lib/zothero/core.py", line 166, in stale
    if self.index.empty:
       ^^^^^^^^^^
  File "/Users/farisal-mawwashi/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.E5ECFFE7-697F-4C98-91B0-47D2F8146ED3/lib/zothero/core.py", line 159, in index
    self._index.update(self.zotero)
  File "/Users/farisal-mawwashi/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.E5ECFFE7-697F-4C98-91B0-47D2F8146ED3/lib/zothero/index.py", line 277, in update
    if not self._update(zot, force):
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/farisal-mawwashi/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.E5ECFFE7-697F-4C98-91B0-47D2F8146ED3/lib/zothero/index.py", line 325, in _update
    for e in it:
  File "/Users/farisal-mawwashi/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.E5ECFFE7-697F-4C98-91B0-47D2F8146ED3/lib/zothero/zotero.py", line 292, in all_entries
    yield self._load_entry(row)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/farisal-mawwashi/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.E5ECFFE7-697F-4C98-91B0-47D2F8146ED3/lib/zothero/zotero.py", line 344, in _load_entry
    e.citekey = self.bbt.citekey('{}_{}'.format(e.library, e.key))
                ^^^^^^^^
  File "/Users/farisal-mawwashi/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.E5ECFFE7-697F-4C98-91B0-47D2F8146ED3/lib/zothero/zotero.py", line 209, in bbt
    self.bibpath_copy = copyifnewer(self.originalBib, self.bibpath)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/farisal-mawwashi/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.E5ECFFE7-697F-4C98-91B0-47D2F8146ED3/lib/zothero/util.py", line 153, in copyifnewer
    copyfile(source, copy)
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/shutil.py", line 256, in copyfile
    with open(src, 'rb') as fsrc:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/farisal-mawwashi/Zotero/better-bibtex.sqlite'
14:36:18 workflow.py:2116 INFO     for assistance, see: https://github.com/giovannicoppola/zothero/issues
14:36:18 workflow.py:2136 DEBUG    ---------- finished in 0.028s ----------
[14:36:18.523] ZotHero[Script Filter] {
  "items": [
    {
      "title": "Error in workflow 'ZotHero'",
      "subtitle": "[Errno 2] No such file or directory: '/Users/farisal-mawwashi/Zotero/better-bibtex.sqlite'",
      "valid": false,
      "icon": {
        "path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
      }
    }
  ]
}
<img width="751" alt="Screenshot 2023-07-21 at 2 43 16 PM" src="https://github.com/giovannicoppola/zothero/assets/132656986/872326c2-c590-4098-81b4-d0823dbe97b1">
<img width="751" alt="Screenshot 2023-07-21 at 2 43 16 PM" src="https://github.com/giovannicoppola/zothero/assets/132656986/c89c10de-307a-402c-9db0-1033a08aa61c">

**Comment by Wulin-Tan** [comment]
@Faris-2023 same issue!

**Comment by Faris-2023** [comment]
@Wulin-Tan and no one answer!

**Comment by help-moo** [comment]
Same issue here

**Comment by burgershot** [comment]
Installing this extension fixed the issue

https://retorque.re/zotero-better-bibtex/installation/

**Comment by giovannicoppola** [comment]
@Faris-2023  I had replied with the solution on July 21  on the Alfred mailing list, unfortunately I had not seen these messages. 
https://www.alfredforum.com/topic/11658-zothero-%E2%80%94-generate-zotero-citations-in-alfred/?do=findComment&comment=107411

Glad it is solved, I will now close this issue.
